### ISSUE TITLE
Stateful containers are recreated when they are launched directly

### ISSUE THREAD

**Issue by davidgiesberg** [twitter-fabric/galley#35]
I'm seeing a behavior that doesn't seem to line up with how I _expect_ galley to behave.

**Expectation**

Setting a service to be stateful should mean that the _only_ time it gets nuked is when I explicitly tell galley to do so (with `unprotectStateful` and the like)

**Observation**

`database` is a stateful service that is a dependency of `app`:

    $ galley run app.dev
    database: Checking… not found. Creating… done! Starting… done!
    app: Checking… not found. Creating… done! Starting… done!

Make some changes so `database`'s state has changed

    $ galley run database.dev
    database: Checking… needs recreate Removing… done! Creating… done! Starting… done!

Now, `database`'s state has been lost, when I was just expecting it to relaunch in the foreground.

PR is en route

**Comment by phopkins** [comment]
Left some comments on #36. I think it's ok to redefine stateful to not recreate even when it's primary, though I worry that that imposes some significant limitations on how well Galley can get it in a good state for you. It may be better to tweak things so that you don't typically want to run stateful containers as primary.

**Comment by davidgiesberg** [comment]
Update: I've made some changes to our workflow, so we're now using data volume containers - that addresses the original problem that I had and in a way that seems a bit more sane. I'm happy to defer to others on how/when state should be preserved.
